version: "3.8"

services:
  video-app:
    build: 
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

